sportbar/app_cart/urls.py
from django.urls import path


from app_cart.views import cart_add, cart, cart_remove, CreateOrder, OrdersList

app_name = "cart"

urlpatterns = [
    path("", cart, name="cart"),
    path("add/<int:id>/", cart_add, name="add-to-cart"),
    path("delete/<int:product_id>/", cart_remove, name="move-off-cart"),
    path("order_form/", CreateOrder.as_view(), name="order-form"),
    path("orders/", OrdersList.as_view(), name="orders-list"),
]

sportbar/app_sportbar/urls.py
from django.urls import path
from .views import (
    index,
    CategoryDetailView,
    ClientCreateView,
    BookedTableCreateView,
    BookedTableListView,
    BookedTableUpdateView,
    BookedTableDeleteView,
)

app_name = "sportbar"

urlpatterns = [
    path("", index, name="home"),
    path(
        "categories/<str:slug>",
        CategoryDetailView.as_view(),
        name="category"
    ),
    path("register/", ClientCreateView.as_view(), name="register"),
    path(
        "booked_table/<int:match_id>",
        BookedTableCreateView.as_view(),
        name="booked-table",
    ),
    path(
        "booked_table_list/",
        BookedTableListView.as_view(),
        name="booked-table-list"
    ),
    path(
        "booked_table_update/<int:pk>/",
        BookedTableUpdateView.as_view(),
        name="booked-table-update",
    ),
    path(
        "booked_table_delete/<int:pk>/",
        BookedTableDeleteView.as_view(),
        name="booked-table-delete",
    ),
]

sportbar/sportbar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("app_sportbar.urls", namespace="app_sportbar")),
    path("cart/", include("app_cart.urls", namespace="cart")),
    path("accounts/", include("django.contrib.auth.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

sportbar/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset=utf-8>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>
    {% block title %}Sportbar{% endblock title %}
  </title>


  <!-- Load Roboto font -->
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,700&amp;subset=latin,latin-ext' rel='stylesheet'
    type='text/css'>
  <!-- Load css styles -->
  <link rel="stylesheet" type="text/css" href="{% static 'app_sportbar/css/bootstrap.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app_sportbar/css/bootstrap-responsive.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app_sportbar/css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app_sportbar/css/pluton.css' %}" />
  <!--[if IE 7]>
  <link rel="stylesheet" type="text/css" href="{% static 'app_sportbar/css/pluton-ie7.css' %}"/>
  <![endif]-->
  <link rel="stylesheet" type="text/css" href="{% static 'app_sportbar/css/jquery.cslider.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app_sportbar/css/jquery.bxslider.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'app_sportbar/css/animate.css' %}" />
  <!-- Fav and touch icons -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144"
    href="{% static 'app_sportbar/images/ico/apple-touch-icon-144.png' %}">
  <link rel="apple-touch-icon-precomposed" sizes="114x114"
    href="{% static 'app_sportbar/images/ico/apple-touch-icon-114.png' %}">
  <link rel="apple-touch-icon-precomposed" sizes="72x72"
    href="{% static 'app_sportbar/images/apple-touch-icon-72.png' %}">
  <link rel="apple-touch-icon-precomposed" href="{% static 'app_sportbar/images/ico/apple-touch-icon-57.png' %}">
  <link rel="shortcut icon" href="{% static 'app_sportbar/images/ico/favicon.ico' %}">
</head>

<body>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <a href="#" class="brand">
          <img src="{% static 'app_sportbar/images/logo.png' %}" alt="Logo" />
          <!-- This is website logo -->
        </a>
        <!-- Navigation button, visible on small resolution -->
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <i class="icon-menu"></i>
        </button>
        <!-- Main navigation -->
        {% include "includes/navbar.html" %}
        <!-- End main navigation -->
      </div>
    </div>
  </div>
  {% block content %}
  <!-- Start home section -->
  <div id="home">
    <!-- Start cSlider -->
    <div id="da-slider" class="da-slider">
      <div class="triangle"></div>
      <!-- mask elemet use for masking background image -->
      <div class="mask"></div>
      <!-- All slides centred in container element -->
      <div class="container">
        <!-- Start first slide -->
        <div class="da-slide">
          <h2 class="fittext2">Grab Your Beer</h2>
          <h4>WATCH YOUR FAVOURITE GAME</h4>
          <p>Welcome to the highly-anticipated sports bar ranked first among many of the
            most popular nighttime destinations. Enjoy the latest sporting events and drink cold beer at our
            bar!</p>
          <a href="#" class="da-link button">Read more</a>
          <div class="da-img">
            <img src="{% static 'app_sportbar/images/close-up-friends.avif' %}" width="320" alt="image02">
          </div>
        </div>
        <!-- End first slide -->
        <!-- Start second slide -->
        <div class="da-slide">
          <h2>Enjoy The Game</h2>
          <h4>THE BIG SCREEN EXPERIENCE</h4>
          <p>We have one of the biggest LED TV panels in the city and that’s why watching
            your favorite game at The Sport Bar guarantees you will enjoy your time.</p>
          <a href="#" class="da-link button">Read more</a>
          <div class="da-img">
            <img src="{% static 'app_sportbar/images/fun.jpg' %}" width="320" alt="image02">
          </div>
        </div>
        <!-- End second slide -->
        <!-- Start third slide -->
        <div class="da-slide">
          <h2>Great Place For Everyone</h2>
          <h4>Enjoy Your Company</h4>
          <p>A good company is what you need to unforgettably spend your time at our bar.
            With a wide variety of snacks and drinks, you and your friends can have the best sports bar
            experience.</p>
          <a href="#" class="da-link button">Read more</a>
          <div class="da-img">
            <img src="{% static 'app_sportbar/images/happy-men.avif' %}" width="320" alt="image02">
          </div>
        </div>
        <!-- Start third slide -->
        <!-- Start cSlide navigation arrows -->
        <div class="da-arrows">
          <span class="da-arrows-prev"></span>
          <span class="da-arrows-next"></span>
        </div>
        <!-- End cSlide navigation arrows -->
      </div>
    </div>
  </div>
  <!-- End home section -->


  <!-- Matches section start -->
  <div class="section secondary-section " id="matches">
    <div class="triangle"></div>
    <div class="container">
      <div class=" title">
        <h1>UPCOMING EVENTS</h1>
        <p>You're always welcome to watch the most exciting matches</p>
      </div>
      <ul class="nav nav-pills">
        <li class="filter" data-filter="all">
          <a href="#noAction">All</a>
        </li>
        {% for championship in championships %}
        <li class="filter" data-filter="{{championship.title}}">
          <a href="#noAction">{{championship.title}}</a>
        </li>
        {% endfor %}
      </ul>
      <!-- Start details for portfolio project 1 -->
      <div id="single-project">
        {% for match in matches %}
        <div id="slidingDiv{{match.id}}" class="toggleDiv row-fluid single-project">
          <div class="span6">
            <img src="{{match.poster.url}}" alt="project 2222">
          </div>
          <div class="span6">
            <div class="project-description">
              <div class="project-title clearfix">
                <h3>{{match.title}}</h3>
                <span class="show_hide close">
                  <i class="icon-cancel"></i>
                </span>
              </div>
              <div class="project-info">
                <div>
                  <span>Competition</span>{{match.championship}}
                </div>
                <div>
                  <span>Date</span>{{match.event_date}}
                </div>
                <div>
                  <span>Preview</span>{{match.preview}}
                </div>
                <a href="{% url 'app_sportbar:booked-table' match.pk %}">
                  <button type="button" class="btn btn-success">Book a table</button>
                </a>
              </div>
              <p>{{category.description}}</p>
            </div>
          </div>
        </div>
        {% endfor %}
        <!-- End details for portfolio project 9 -->
        <ul id="portfolio-grid" class="thumbnails row">
          {% for match in matches %}
          <li class="span4 mix {{match.championship}}">
            <div class="thumbnail">
              <img src="{{match.poster.url}}" alt="match {{match.pk}}">
              <a href="#single-project" class="more show_hide" rel="#slidingDiv{{match.pk}}">
                <i class="icon-plus"></i>
              </a>
              <h3>{{match.title}}</h3>
              <p>{{match.event_date}}</p>
              <div class="mask"></div>
            </div>
          </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  <!-- Matches section end -->


  <!-- Categories section start -->
  <div class="section primary-section" id="categories">
    <div class="triangle"></div>
    <div class="container">
      <div class="title">
        <h1>Categories</h1>
        <p>Order food to your home</p>
      </div>

      <div class="row-fluid team">
        {% for category in categories %}
        <div class="span4 mg-left0" id="category{{category.id}}">
          <div class="thumbnail">
            <img src="{{category.image.url}}" alt="team 1">
            <h3>{{category.title}}</h3>
            <div class="mask">
              <h2>{{category.description}}</h2>
              <a href="{{category.get_absolute_url}}">
                <button type="button" class="btn btn-success">Choose and order {{category.title}}</button>
              </a>
            </div>
          </div>
        </div>
        {% endfor %}

      </div>

    </div>
  </div>
  <!-- Categories section end -->

  <div class="section secondary-section">
    <div class="triangle"></div>
    <div class="container centered">
      <p class="large-text">Elegance is not the abundance of simplicity. It is the absence of complexity.</p>
      <a href="#" class="button">Purshase now</a>
    </div>
  </div>
  {% endblock %}


  <!-- Contact section start -->
  <div id="contact" class="contact">
    <div class="section secondary-section">
      <div class="container">
        <div class="title">
          <h1>Contact Us</h1>
          <p>Duis mollis placerat quam, eget laoreet tellus tempor eu. Quisque dapibus in purus in dignissim.
          </p>
        </div>
      </div>

      <div class="container">
        <div class="span9 center contact-info">
          <p>123 Fifth Avenue, 12th,Belgrade,SRB 11000</p>
          <p class="info-mail">sportbar@somemail.com</p>
          <p>+11 234 567 890</p>
          <p>+11 286 543 850</p>
          <div class="title">
            <h3>We Are Social</h3>
          </div>
        </div>
        <div class="row-fluid centered">
          <ul class="social">
            <li>
              <a href="">
                <span class="icon-facebook-circled"></span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="icon-twitter-circled"></span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="icon-linkedin-circled"></span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="icon-pinterest-circled"></span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="icon-dribbble-circled"></span>
              </a>
            </li>
            <li>
              <a href="">
                <span class="icon-gplus-circled"></span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- Contact section edn -->
  <!-- Footer section start -->
  <div class="footer">
    <p>&copy; 2013 Theme by <a href="http://www.graphberry.com">GraphBerry</a>, <a
        href="http://goo.gl/NM84K2">Documentation</a></p>
  </div>
  <!-- Footer section end -->
  <!-- ScrollUp button start -->
  <div class="scrollup">
    <a href="#">
      <i class="icon-up-open"></i>
    </a>
  </div>
  <!-- ScrollUp button end -->
  <!-- Include javascript -->
  <script src="{% static 'app_sportbar/js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'app_sportbar/js/jquery.mixitup.js' %}"></script>
  <script type="text/javascript" src="{% static 'app_sportbar/js/bootstrap.js' %}"></script>
  <script type="text/javascript" src="{% static 'app_sportbar/js/modernizr.custom.js' %}"></script>
  <script type="text/javascript" src="{% static 'app_sportbar/js/jquery.bxslider.js' %}"></script>
  <script type="text/javascript" src="{% static 'app_sportbar/js/jquery.cslider.js' %}"></script>
  <script type="text/javascript" src="{% static 'app_sportbar/js/jquery.placeholder.js' %}"></script>
  <script type="text/javascript" src="{% static 'app_sportbar/js/jquery.inview.js' %}"></script>
  <!-- Load google maps api and call initializeMap function defined in app.js -->
  <script async="" defer="" type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?sensor=false&callback=initializeMap"></script>
  <!-- css3-mediaqueries.js for IE8 or older -->
  <!--[if lt IE 9]>
<script src="{% static 'app_sportbar/js/respond.min.js' %}"></script>
<![endif]-->
  <script type="text/javascript" src="{% static 'app_sportbar/js/app.js' %}"></script>
</body>

</html>