sportbar/app_cart/urls.py
from django.urls import path


from app_cart.views import cart_add, cart, cart_remove, CreateOrder, OrdersList

app_name = "cart"

urlpatterns = [
    path("", cart, name="cart"),
    path("add/<int:id>/", cart_add, name="add-to-cart"),
    path("delete/<int:product_id>/", cart_remove, name="move-off-cart"),
    path("order_form/", CreateOrder.as_view(), name="order-form"),
    path("orders/", OrdersList.as_view(), name="orders-list"),
]

sportbar/app_sportbar/urls.py
from django.urls import path
from .views import (
    index,
    CategoryDetailView,
    ClientCreateView,
    BookedTableCreateView,
    BookedTableListView,
    BookedTableUpdateView,
    BookedTableDeleteView,
)

app_name = "sportbar"

urlpatterns = [
    path("", index, name="home"),
    path(
        "categories/<str:slug>",
        CategoryDetailView.as_view(),
        name="category"
    ),
    path("register/", ClientCreateView.as_view(), name="register"),
    path(
        "booked_table/<int:match_id>",
        BookedTableCreateView.as_view(),
        name="booked-table",
    ),
    path(
        "booked_table_list/",
        BookedTableListView.as_view(),
        name="booked-table-list"
    ),
    path(
        "booked_table_update/<int:pk>/",
        BookedTableUpdateView.as_view(),
        name="booked-table-update",
    ),
    path(
        "booked_table_delete/<int:pk>/",
        BookedTableDeleteView.as_view(),
        name="booked-table-delete",
    ),
]

sportbar/sportbar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("app_sportbar.urls", namespace="app_sportbar")),
    path("cart/", include("app_cart.urls", namespace="cart")),
    path("accounts/", include("django.contrib.auth.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

sportbar/templates/includes/navbar.html
{% load static %}

{% load cart_custom_tags %}
{% cart_length as cart_length %}

{% load sportbar_custom_tags %}
{% booked_tables_quantity as booked_tables_quantity %}
<!-- Main navigation -->
<div class="nav-collapse collapse pull-right">
  <ul class="nav" id="top-navigation">
    <li class="active"><a href="{% url 'sportbar:home' %}#home">Home</a></li>
    <li><a href="{% url 'sportbar:home' %}#matches">Matches</a></li>
    <li><a href="{% url 'sportbar:home' %}#categories">Delivery</a></li>
    <li><a href="{% url 'sportbar:home' %}#contact">Contact</a></li>
    {% if request.user.is_authenticated %}
    <li>
      <a href="#home">
        <button type="button" class="btn btn-success">{{ request.user }}
          {% if request.user.avatar %}
          <img src="{{ request.user.avatar.url }}" width="30">
          {% endif %}
        </button>
      </a>
    </li>
    <li>
      <a href="{% url 'logout' %}">
        <button type="button" class="btn btn-success">Logout</button>
      </a>
    </li>
    <li>
      <a href="{% url 'sportbar:booked-table-list' %}">
        {% if request.user.booked_tables %}

        {% if booked_tables_quantity > 0 %}
        {{ booked_tables_quantity }}

        {% endif %}

        <img src="{% static 'app_sportbar/images/tickets.png' %}" width="30">
        {% endif %}
      </a>
    </li>
    {% else %}
    <li>
      <a href="{% url 'sportbar:register' %}">
        <button type="button" class="btn btn-success">Register</button>
      </a>
    </li>
    <li>
      <a href="{% url 'login' %}">
        <button type="button" class="btn btn-success">Log in</button>
      </a>
    </li>
    {% endif %}
    <li>
      <a href="{% url 'cart:cart' %}">

        {% if cart_length %}
        {% cart_length %}
        <img src="{% static 'app_cart/images/cart.png' %}" width="30">
        {% else %}
        <img src="{% static 'app_cart/images/empty_cart.png' %}" width="30">
        {% endif %}


      </a>
    </li>

  </ul>

</div>

<!-- End main navigation -->