sportbar/app_cart/urls.py
from django.urls import path


from app_cart.views import cart_add, cart, cart_remove, CreateOrder, OrdersList

app_name = "cart"

urlpatterns = [
    path("", cart, name="cart"),
    path("add/<int:id>/", cart_add, name="add-to-cart"),
    path("delete/<int:product_id>/", cart_remove, name="move-off-cart"),
    path("order_form/", CreateOrder.as_view(), name="order-form"),
    path("orders/", OrdersList.as_view(), name="orders-list"),
]

sportbar/app_sportbar/urls.py
from django.urls import path
from .views import (
    index,
    CategoryDetailView,
    ClientCreateView,
    BookedTableCreateView,
    BookedTableListView,
    BookedTableUpdateView,
    BookedTableDeleteView,
)

app_name = "sportbar"

urlpatterns = [
    path("", index, name="home"),
    path(
        "categories/<str:slug>",
        CategoryDetailView.as_view(),
        name="category"
    ),
    path("register/", ClientCreateView.as_view(), name="register"),
    path(
        "booked_table/<int:match_id>",
        BookedTableCreateView.as_view(),
        name="booked-table",
    ),
    path(
        "booked_table_list/",
        BookedTableListView.as_view(),
        name="booked-table-list"
    ),
    path(
        "booked_table_update/<int:pk>/",
        BookedTableUpdateView.as_view(),
        name="booked-table-update",
    ),
    path(
        "booked_table_delete/<int:pk>/",
        BookedTableDeleteView.as_view(),
        name="booked-table-delete",
    ),
]

sportbar/sportbar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("app_sportbar.urls", namespace="app_sportbar")),
    path("cart/", include("app_cart.urls", namespace="cart")),
    path("accounts/", include("django.contrib.auth.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

sportbar/app_sportbar/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import UniqueConstraint
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(
        upload_to="images/%Y/%m/%d",
        max_length=100,
        blank=True,
        null=True,
        default="images/2024/02/17/beer.jpg",
    )
    description = models.CharField(max_length=150, blank=True, null=True)
    slug = models.SlugField(max_length=50)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("app_sportbar:category", kwargs={"slug": self.slug})


class MenuPosition(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=150, blank=True, null=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="menu_positions"
    )
    image = models.ImageField(
        upload_to="images/%Y/%m/%d", max_length=100, blank=True, null=True
    )
    slug = models.SlugField(max_length=50, unique=True, blank=True, null=True)

    def __str__(self):
        return self.title


class Match(models.Model):
    title = models.CharField(max_length=250)
    championship = models.ForeignKey("Championship", on_delete=models.CASCADE)
    event_date = models.DateTimeField()
    preview = models.TextField(blank=True, null=True)
    poster = models.ImageField(
        upload_to="images/match_poster/%Y/%m/%d",
        max_length=100,
        blank=True,
        null=True,
        default="images/match_poster/stadium.jpg",
    )

    def __str__(self):
        return f"{self.title} - {self.event_date.strftime('%M/%d %H:%M')}"


class Championship(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title


class Client(AbstractUser):
    avatar = models.ImageField(
        upload_to="images/avatars/%Y/%m/%d",
        blank=True,
        null=True,
        max_length=250,
    )


class BookedTable(models.Model):
    client = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="booked_tables",
    )
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    phone = models.CharField(
        max_length=10,
        validators=[
            RegexValidator(
                regex=r"^\d{10}$",
                message="phone number should consists of 10 figures",
            )
        ],
    )

    class Meta:
        constraints = [
            UniqueConstraint(
                fields=["client", "match"],
                name="this match is already booked",
            )
        ]

sportbar/app_sportbar/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import RegexValidator

from app_sportbar.models import BookedTable


class ClientCreationForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for fieldname in ["username", "password1", "password2"]:
            self.fields[fieldname].help_text = None

    class Meta:
        model = get_user_model()
        fields = ("username", "password1", "password2", "avatar")


class BookedTableForm(forms.ModelForm):
    phone = forms.CharField(
        validators=[
            RegexValidator(
                regex=r"^\d{10}$",
                message="phone number should consists of 10 figures"
            )
        ]
    )

    class Meta:
        model = BookedTable
        fields = ["phone", "match", "client"]
        widgets = {"match": forms.HiddenInput(), "client": forms.HiddenInput()}

sportbar/app_sportbar/views.py
from datetime import timedelta

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.http import JsonResponse

from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    DetailView,
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
)

from app_cart.forms import CartAddProductForm
from .forms import ClientCreationForm, BookedTableForm
from .models import Category, Match, Championship, BookedTable


def index(request):
    return render(
        request,
        "base.html",
        {
            "championships": Championship.objects.all(),
            "categories": Category.objects.all(),
            "matches": Match.objects.select_related("championship"),
        },
    )


class CategoryDetailView(DetailView):
    model = Category

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cart_add_form"] = CartAddProductForm()

        paginator = Paginator(self.object.menu_positions.all(), 3)
        context["page_obj"] = paginator.get_page(self.request.GET.get("page"))
        return context


class ClientCreateView(CreateView):
    model = get_user_model()
    form_class = ClientCreationForm
    success_url = reverse_lazy("login")


class BookedTableCreateView(LoginRequiredMixin, CreateView):
    form_class = BookedTableForm
    template_name = "app_sportbar/booked_table_form.html"
    success_url = reverse_lazy("sportbar:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if BookedTable.objects.filter(
                match_id=self.kwargs["match_id"]
        ).count() < settings.MAX_BAR_CAPACITY:
            initial_data = {"match": self.kwargs["match_id"],
                            "client": self.request.user}
            context["form"] = BookedTableForm(initial_data)
        else:
            del context["form"]
            context["excess_error"] = "Everything is booked for this match."
        return context

    def post(self, request, *args, **kwargs):
        form = BookedTableForm(self.request.POST)
        if form.is_valid():
            booked_table = form.save()
            match = booked_table.match.title
            booked_time = booked_table.match.event_date
            before = timedelta(hours=1)
            after = timedelta(hours=2.5)
            return JsonResponse(
                {
                    "message": "success",
                    "match": match,
                    "from": (booked_time - before).strftime("%Y %B %d %H:%M"),
                    "to": (booked_time + after).strftime("%Y %B %d %H:%M"),
                },
                status=200,
            )
        else:
            return JsonResponse({"message": "error"}, status=400)


class BookedTableListView(LoginRequiredMixin, ListView):
    model = BookedTable
    template_name = "app_sportbar/booked_table_list.html"

    def get_queryset(self):
        return self.model.objects.filter(client=self.request.user)


class BookedTableUpdateView(LoginRequiredMixin, UpdateView):
    model = BookedTable
    fields = ("match", "phone")
    template_name = "app_sportbar/booked_table_update.html"
    success_url = reverse_lazy("sportbar:home")

    def post(self, *args, **kwargs):
        try:
            self.object = self.get_object()
            self.object.phone = self.request.POST.get("phone")
            self.object.match_id = self.request.POST.get("match")
            self.object.save()
        except IntegrityError:
            pass
        return redirect(reverse("sportbar:booked-table-list"))


class BookedTableDeleteView(LoginRequiredMixin, DeleteView):
    model = BookedTable
    template_name = "app_sportbar/booked_table_delete.html"
    success_url = reverse_lazy("sportbar:booked-table-list")

sportbar/app_sportbar/templates/app_sportbar/booked_table_delete.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form class="form-added" method="post">
  {% csrf_token %}
    <h1>Here you can cancel you booking for</h1>
    <h2>{{ object.match.title }}</h2>
    <button type="submit" class="btn btn-danger">Cancel my booking</button>
  </form>
{% endblock %}

sportbar/app_sportbar/templates/app_sportbar/booked_table_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1 class="form-added" id="matchUserConstraint">We need your phone number to confirm your reservation </h1>
  <form class="form-added" method="post" id="book_table_form">
    {% csrf_token %}
    {{ form|crispy }}
    <div id="phoneError"></div>
    <button type="submit" class="btn-success ">Book a table</button>
  </form>

  {#  Start-error if no table available#}
  <div class="form-added" id="excessError">{{ excess_error }}</div>
  {#  End-error if no table available#}

  <!-- Start-Modal -->
  <div class="modal form-added" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
       aria-labelledby="staticBackdropLabel" aria-hidden="true" style="left: 24%; display: none">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
        </div>
        <div class="modal-body" id="timeGap">

        </div>
        <div class="modal-footer">
          <a href="{% url 'sportbar:home' %}">
            <button type="button" class="btn btn-primary">Cool!!!</button>
          </a>
        </div>
      </div>
    </div>
  </div>
  <!-- End-Modal -->

  <script>

      {#Start-check if already the match booked from Uniqueconstraint#}
      if (document.querySelector(".alert.alert-block.alert-danger")) {
          book_table_form.style.display = "none";
          matchUserConstraint.innerText = " You have already booked table for this match"
      }
      {#End-check if already the match booked from Uniqueconstraint#}

      <!--Start-not display form if excessError-->
      if(document.getElementById("excessError").innerText){
          book_table_form.style.display = "none"
          matchUserConstraint.style.display = "none"
      }
      <!--End-enot display form if excessError-->

      {#Start-send fetch request for modal confirmation#}
      function sendRequestFetchPost(method, url, body) {
          fetch(url, {
              method: method,
              body: body,
              headers: {"X-Requested-With": "XMLHttpRequest"}
          })
              .then((response) => response.json())
              .then((data) => {
                  if (data.message == "success") {
                      staticBackdrop.style.display = "block"
                      staticBackdropLabel.innerText = `You have successfully booked table for ${data.match}!
                      We wish your team to win.`;
                      phoneError.innerText = '';
                      timeGap.innerText = `Your table is available from ${data.from} till ${data.to}`
                  } else {
                      phoneError.innerText = 'Valid phone number consists of 10 digits';
                  }
              })
      }

      book_table_form.addEventListener('submit', function fetchSubmit(event) {
          event.preventDefault();
          sendRequestFetchPost("POST", this.action, new FormData(this))
      })
      {#End-send fetch request for modal confirmation#}
  </script>

{% endblock %}

sportbar/app_sportbar/templates/app_sportbar/booked_table_list.html
{% extends "base.html" %}
{% load sportbar_custom_tags %}


{% block title %}
Your events
{% endblock title %}

{% block content %}
{% booked_tables_quantity as booked_tables_quantity %}


{% if booked_tables_quantity > 0 %}
  <h1>Your event list</h1>


<table class="table align-middle mb-0 bg-white form-added">
  <thead class="bg-light">
    <tr>
      <th>#</th>
      <th>Event</th>
      <th>Kick off</th>
      <th>Booked time</th>
      <th>Change</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    {% if object_list == "<QuerySet []>" %}
      oiuio
      {% endif %}
      {% for booked_table in object_list %}
      <tr>
        <td>
          {{ forloop.counter }}
        </td>
        <td>
          <div class="d-flex align-items-center">
            <img src="{{ booked_table.match.poster.url }}" alt="" style="width: 45px; height: 45px"
              class="rounded-circle" />
            <div class="ms-3">
              <p class="fw-bold mb-1">{{ booked_table.match.title }}</p>
            </div>
          </div>
        </td>
        <td>
          <p class="fw-normal mb-1">{{ booked_table.match.event_date|date:"l - M j Y g.i A" }}</p>
        </td>
        <td>
          <p class="fw-normal mb-1">{{ booked_table.match.event_date|duration_filter }}</p>
        </td>
        <td>
          <p class="fw-normal mb-1">
            <a href="{% url 'sportbar:booked-table-update' booked_table.pk %}">
              <button type="button" class="btn btn-secondary">Change</button>
            </a>
          </p>
        </td>
        <td>
          <p class="fw-normal mb-1">
            <a href="{% url 'sportbar:booked-table-delete' booked_table.pk %}">
              <button type="button" class="btn btn-danger">Delete</button>
            </a>
          </p>
        </td>
      </tr>
      {% endfor %}
  </tbody>
</table>
</div>
{% else %}
<div class="form-added">
  <h2>No matches selected</h2>
  <a href="{% url 'sportbar:home' %}#matches">
    <button type="button" class="btn btn-success">Select some</button>
  </a>
</div>
{% endif %}
{% endblock %}

sportbar/app_sportbar/templates/app_sportbar/booked_table_update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
<h1>Here you can change the match you booked table for.</h1>
  <form method="post" class="form-added">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-success">Change match</button>
  </form>
{% endblock %}

sportbar/app_sportbar/templates/app_sportbar/category_detail.html
{% extends "base.html" %}

{% block title %}
  {{ object }}
{% endblock title %}


{% block content %}

  <div class="section primary-section" id="categories">
    <div class="triangle"></div>
    <div class="container">
      <div class="title">
        <h1>{{ object }}</h1>
        <p>Order some and get it at home</p>
      </div>

      <div class="row-fluid team">
        {% for position in page_obj.object_list %}
          <div class="span4 mg-left0" id="category{{ category.id }}">
            <div class="thumbnail">
              <img src="{{ position.image.url }}" alt="team 1">
              <h3>{{ position.title }}</h3>
              <div class="mask">
                <h2>{{ position.description }}</h2>
                <h2>{{ position.price }}$</h2>
                <form action="{% url 'cart:add-to-cart' position.pk %}" method="post">
                  {% csrf_token %}
                  {{ cart_add_form }}
                  <input type="submit" value="Add to cart" class="btn btn-primary">
                </form>
              </div>
            </div>
          </div>
        {% endfor %}

      </div>

    </div>
  </div>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page=1">First</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        </li>
      {% endif %}

      {% for p in page_obj.paginator.page_range %}
        {% if page_obj.number == p %}
          <li class="page-item active"><a class="page-link disabled" href="#">{{ p }}</a></li>
        {% elif p > page_obj.number|add:-3 and p < page_obj.number|add:3 %}
          <li class="page-item"><a class="page-link" href="?page={{ p }}">{{ p }}</a></li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        </li>
      {% endif %}
    </ul>
  </nav>

{% endblock %}

sportbar/app_sportbar/templates/app_sportbar/client_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}

<h1 class="form-added">Registration page</h1>
<form method="post" class="form-added" enctype="multipart/form-data">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-success"> Get registered</button>
</form>


{% endblock %}