sportbar/app_cart/urls.py
from django.urls import path


from app_cart.views import cart_add, cart, cart_remove, CreateOrder, OrdersList

app_name = "cart"

urlpatterns = [
    path("", cart, name="cart"),
    path("add/<int:id>/", cart_add, name="add-to-cart"),
    path("delete/<int:product_id>/", cart_remove, name="move-off-cart"),
    path("order_form/", CreateOrder.as_view(), name="order-form"),
    path("orders/", OrdersList.as_view(), name="orders-list"),
]

sportbar/app_sportbar/urls.py
from django.urls import path
from .views import (
    index,
    CategoryDetailView,
    ClientCreateView,
    BookedTableCreateView,
    BookedTableListView,
    BookedTableUpdateView,
    BookedTableDeleteView,
)

app_name = "sportbar"

urlpatterns = [
    path("", index, name="home"),
    path(
        "categories/<str:slug>",
        CategoryDetailView.as_view(),
        name="category"
    ),
    path("register/", ClientCreateView.as_view(), name="register"),
    path(
        "booked_table/<int:match_id>",
        BookedTableCreateView.as_view(),
        name="booked-table",
    ),
    path(
        "booked_table_list/",
        BookedTableListView.as_view(),
        name="booked-table-list"
    ),
    path(
        "booked_table_update/<int:pk>/",
        BookedTableUpdateView.as_view(),
        name="booked-table-update",
    ),
    path(
        "booked_table_delete/<int:pk>/",
        BookedTableDeleteView.as_view(),
        name="booked-table-delete",
    ),
]

sportbar/sportbar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("app_sportbar.urls", namespace="app_sportbar")),
    path("cart/", include("app_cart.urls", namespace="cart")),
    path("accounts/", include("django.contrib.auth.urls")),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

sportbar/app_cart/models.py
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models

from app_sportbar.models import MenuPosition


class Order(models.Model):
    client = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True
    )
    phone = models.TextField(
        validators=[
            RegexValidator(
                regex=r"^\d{10}$",
                message="phone number should consists of 10 figures",
            )
        ]
    )
    address = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    deliver_by = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_delivered = models.BooleanField(default=False)
    is_paid = models.BooleanField(default=False)

    # total order cost with get_cost() from related Model OrderItem
    def get_total_cost(self):
        return sum(item.get_cost() for item in self.order_items.all())

    def __str__(self):
        return "Order {}".format(self.id)

    class Meta:
        ordering = ("-created_at",)


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name="order_items", on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        MenuPosition,
        related_name="products_in_order",
        on_delete=models.CASCADE,
    )
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return "{}".format(self.id)

    def get_cost(self):
        return self.price * self.quantity

sportbar/app_cart/forms.py
from django import forms
from django.core.validators import RegexValidator

from app_cart.models import Order


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(
        min_value=1, widget=forms.NumberInput(attrs={"style": "width:10%"})
    )
    update_quantity = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput
    )


class OrderForm(forms.ModelForm):
    phone = forms.CharField(
        validators=[
            RegexValidator(
                regex=r"^\d{10}$",
                message="phone number should consists of 10 figures"
            )
        ]
    )

    class Meta:
        model = Order
        fields = ("deliver_by", "address", "phone")
        widgets = {"deliver_by": forms.DateTimeInput(
            attrs={"type": "datetime-local"}
        )}

sportbar/app_cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from app_cart.forms import CartAddProductForm, OrderForm
from app_cart.models import OrderItem, Order
from app_sportbar.models import MenuPosition
from app_cart.cart import Cart


def cart(request):
    cart = Cart(request)
    return render(
        request,
        "cart/cart.html",
        {
            "cart_instance": cart,
        },
    )


def cart_add(request, id):
    cart = Cart(request)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cart.add(product=MenuPosition.objects.get(pk=id), **form.cleaned_data)
        return redirect(request.META.get("HTTP_REFERER"))


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(MenuPosition, id=product_id)
    cart.remove(product)
    return redirect("cart:cart")


class CreateOrder(View):
    def get(self, request):
        order_form = OrderForm()
        return render(
            request,
            "cart/order_form.html",
            {"order_form": order_form}
        )

    def post(self, request):
        order_form = OrderForm(request.POST)
        cart_instance = Cart(request)
        if order_form.is_valid():
            if len(cart_instance) > 0:
                if request.user.is_authenticated:
                    order = order_form.save(commit=False)
                    order.client = request.user
                    order.save()
                else:
                    order = order_form.save()
            for item in cart_instance:
                OrderItem.objects.create(
                    order=order,
                    product=item["product"],
                    price=item["price"],
                    quantity=item["quantity"],
                )
            cart_instance.clear()
        return render(
            request,
            "cart/order_form.html",
            {"order_form": order_form}
        )


class OrdersList(LoginRequiredMixin, ListView):
    model = Order
    template_name = "cart/order_list.html"

    def get_queryset(self):
        return Order.objects.filter(client=self.request.user).prefetch_related(
            "order_items__product"
        )

sportbar/app_cart/templates/cart/cart.html
{% extends "base.html" %}
{% block title %}
Your shopping cart
{% endblock %}
{% block content %}

{% load cart_custom_tags %}
{% cart_length as cart_length %}
{% if cart_length %}

<h1>Your shopping cart</h1>
<div class="table-responsive" style="background-color: #1b1b1b">
  <table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
      <tr>
        <th>#</th>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total price</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart_instance %}
      <tr>
        <td>
          {{ forloop.counter }}
        </td>
        <td>
          <div class="d-flex align-items-center">
            <img src="{{ item.product.image.url }}" alt="" style="width: 45px; height: 45px" class="rounded-circle" />
            <div class="ms-3">
              <p class="fw-bold mb-1">{{ item.product.title }}</p>
            </div>
          </div>
        </td>
        <td>
          <p class="fw-normal mb-1">{{ item.price }}$</p>
        </td>
        <td>
          <form action="{% url 'cart:add-to-cart' item.product.pk %}" method="post" class="editQuantityForm">
            <span class="quantityReal" id="{{ item.product.id }}_quantity">{{ item.quantity }}</span>
            {% csrf_token %}
            <input type="number" name="quantity" min="1" required="" value="{{ item.quantity }}"
              style="display: none; width: 3em; color: #371219" class="quantityEdit">
            <input type="hidden" name="update_quantity" value="True">
            <button type="button" class="btn btn-link btn-rounded btn-sm fw-bold quantityReal"
              onclick="editQuantity(event)">
              Edit
            </button>
            <button type="submit" class="btn btn-link btn-rounded btn-sm fw-bold quantityEdit" style="display: none;">
              Confirm
            </button>
            <button type="button" class="back btn btn-link btn-rounded btn-sm fw-bold quantityEdit"
              style="display: none;" onclick="confirmClose(event)">
              Back
            </button>
          </form>
        </td>
        <td>
          <p class="fw-normal mb-1" id="{{ item.product.id }}_total_price">{{ item.total_price }}$</p>
        </td>
        <td>
          <a href="{% url 'cart:move-off-cart' item.product.pk %}">
            <button type="button" class="btn btn-danger btn-rounded" data-mdb-ripple-color="dark">Remove
              from cart
            </button>
          </a>
        </td>
      </tr>

      {% endfor %}
      <tr>
        <td colspan="4">
          <b>TOTAL</b>
        </td>
        <td><b id="cart_total_cost">{{ cart_instance.get_total_cost }}$</b></td>
      </tr>
    </tbody>
  </table>
  <div style="margin: 0 auto; width: fit-content"><a href="{% url 'cart:order-form' %}">
      <button type="button" class="btn btn-centered btn-success">Order</button>
    </a></div>
</div>



<script>
  // show and hide editQuantityForm while press edit
  function editQuantity(event) {
    for (let element of event.currentTarget.parentElement.getElementsByClassName('quantityEdit')) {
      element.style.display = "inline-block"
    }
    for (let element of event.currentTarget.parentElement.getElementsByClassName('quantityReal')) {
      element.style.display = 'none'
    }
  }

  // show and hide editQuantityForm while press confirm/close
  function confirmClose(event) {
    event.preventDefault(event);
    // show and hide editQuantityForm
    for (let element of event.currentTarget.parentElement.getElementsByClassName('quantityEdit')) {
      element.style.display = 'none'
    }
    for (let element of event.currentTarget.parentElement.getElementsByClassName('quantityReal')) {
      element.style.display = 'inline-block'
    }
  }
</script>
{% else %}
<div class="table-responsive" style="background-color: #1b1b1b">
  <h1>Your cart is empty</h1>
</div>
{% endif %}

<a href="{% url 'cart:orders-list' %}">
  <button type="button" class="btn btn-centered btn-info">Go to your orders</button>
</a>


{% endblock content %}

sportbar/app_cart/templates/cart/order_form.html
{% extends "base.html" %}

{% block content %}
  {% load crispy_forms_filters %}
  {% load cart_custom_tags %}
  {% cart_length as cart_length %}

  {% if cart_length %}
    <form class="form-added" method="post">
      {% csrf_token %}
      <h3>Add information to complete the order</h3>

      {% if not request.user.is_authenticated %}
        <div class="alert alert-danger" role="alert">
          You cannot access your order history if you are not registered. <a href="{% url 'login' %}">Log in</a>/<a
            href="{% url 'sportbar:register' %}">Sign up</a>
        </div>
      {% endif %}
      {{ order_form|crispy }}
      <button type="submit" class="btn btn-success">Complete the order</button>
    </form>
  {% else %}
    <form class="form-added"">
    <h1>We've received your order.</h1>
    <a href="{% url 'cart:orders-list' %}">
      <button type="button" class="btn btn-info">Go to your orders</button>
    </a>
    </form>
  {% endif %}
{% endblock %}

sportbar/app_cart/templates/cart/order_list.html
{% extends 'base.html' %}
{% load cart_custom_tags %}z


{% block title %}
Order history
{% endblock title %}



{% block content %}
{% cart_length as cart_length %}

{% for object in object_list %}
<div class="table-responsive" style="border: 2px white groove; margin:25px; padding: 15px;">
    <div class="class=" d-flex justify-content-start">
        <div>
            Order{{object.pk}}
        </div>
        <div>
            {{object.created_at}}
        </div>
        <div>

            {% if object.is_delivered %}
            <i class="fas fa-check " style="color: rgb(121, 248, 10);"> Delivered</i>
            {% else %}
            <i class="fas fa-car-side" style="color: red;"> NOT delivered</i>
            {% endif %}
          <span>(date to deliver: {{object.deliver_by}})</span>
        </div>
        <div>

            {% if object.is_paid %}
            <i class="fas fa-check" style="color: rgb(121, 248, 10);"> Paid</i>
            {% else %}
            <i class="fas fa-credit-card" style="color: red;"> NOT paid</i>
            {% endif %}
        </div>
    </div>

    <table class="table align-middle mb-0 bg-white form-added">
        <thead class="bg-light">
            <tr>
                <th>#</th>
                <th>Product</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Total price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            {% for order_item in object.order_items.all %}


            <tr>
                <td>
                    {{forloop.counter}}
                </td>
                <td>
                    <div class="d-flex align-items-center">
                        <img src="{{order_item.product.image.url}}" alt="" style="width: 45px; height: 45px"
                            class="rounded-circle" />
                        <div class="ms-3">
                            <p class="fw-bold mb-1">{{order_item.product.title}}</p>
                        </div>
                    </div>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{order_item.price}}$</p>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{order_item.quantity}}</p>
                </td>
                <td>
                    <p class="fw-normal mb-1">{{order_item.get_cost}}$</p>
                </td>
                <td>

                </td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="4">
                    <b>TOTAL</b>
                </td>
                <td><b id="cart_total_cost">{{object.get_total_cost}}$</b></td>
            </tr>
        </tbody>
    </table>
</div>
{% empty %}
<div class="form-added">
    <h2>You don't have any orders completed</h2>
    <a href="{% url 'sportbar:home' %}#categories">
        <button type="button" class="btn btn-success">Select some products</button>
    </a>
    {% if cart_length %}
    <a href="{% url 'cart:cart' %}">
        <button type="button" class="btn btn-success">Go to your cart and make an order</button>
    </a>
    {% endif %}
</div>
{% endfor %}


{% endblock %}